<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Album3\Module'                        => __DIR__ . '/Module.php',
    'Album3\Controller\Album3Controller' => __DIR__ . '/src/Album3/Controller/Album3Controller.php',
    'Album3Test\Framework\TestCase'        => __DIR__ . '/tests/Album3/Framework/TestCase.php',
    'Album3Test\SampleTest'                => __DIR__ . '/tests/Album3/SampleTest.php',
);
