<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Ma\Module'                        => __DIR__ . '/Module.php',
    'Ma\Controller\MaController' => __DIR__ . '/src/Ma/Controller/MaController.php',
    'MaTest\Framework\TestCase'        => __DIR__ . '/tests/Ma/Framework/TestCase.php',
    'MaTest\SampleTest'                => __DIR__ . '/tests/Ma/SampleTest.php',
);
