 <?php 

 /*
 $title = 'My albums';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add new album</a>
 </p>

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>Price</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach (data as $row) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($row->title);?></td>
     <td><?php echo $this->escapeHtml($row->artist);?></td>
     <td><?php echo $this->escapeHtml($row->price);?></td>
     <td>
         <a href="<?php echo $this->url('album',
             array('action'=>'edit', 'id' => $row->id));?>">Edit</a>
         <a href="<?php echo $this->url('album',
             array('action'=>'delete', 'id' => $row->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
*/
 ?>
 <?php
 echo $xxx;
 echo $data;

 ?>